<a href="https://colab.research.google.com/github/ohsang14/school_python/blob/main/3%EC%9B%9411%EC%9D%BC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

arr = np.array([1,2,3])
print(arr)
print(type(arr))



[1 2 3]
<class 'numpy.ndarray'>


In [3]:
import numpy as np

arr1 = np.array([1,2,3])
arr1 = arr1+2
print(arr1)

arr1 = arr1 * 2
print(arr1)

[3 4 5]
[ 6  8 10]


In [4]:
import numpy as np

lst1 = [1,2,3]
lst2 = [4,5,6]
print(lst1 + lst2)

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print(arr1 + arr2)


[1, 2, 3, 4, 5, 6]
[5 7 9]


In [5]:
import numpy as np

print(np.arange(10), np.array(range(10)))
print(np.arange(1,10), np.array(range(1,10)))
print(np.arange(0,10,2), np.array(range(0,10,2)))

[0 1 2 3 4 5 6 7 8 9] [0 1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9] [1 2 3 4 5 6 7 8 9]
[0 2 4 6 8] [0 2 4 6 8]


In [6]:
arr =np.eye(4)
print(arr * 10)

[[10.  0.  0.  0.]
 [ 0. 10.  0.  0.]
 [ 0.  0. 10.  0.]
 [ 0.  0.  0. 10.]]


In [7]:
import numpy as np

arr = np.array([1,2,3,4,5])
print(arr[[0,2,4]])
larr = arr >= 3
print(larr)
print(arr[larr])

[1 3 5]
[False False  True  True  True]
[3 4 5]


In [8]:
import numpy as np

arr = np.array([[1,2,3],[4,5,6]])

larr = arr % 2 == 0
print(larr)

print(arr[larr])

[[False  True False]
 [ True False  True]]
[2 4 6]


In [9]:
import numpy as np

arr1 = np.arange(8).reshape(2,4)
arr2 = np.arange(8,16).reshape(2,4)

print(arr1)
print(arr2)
print(np.concatenate((arr1,arr2), axis=0))
print(np.concatenate((arr1,arr2), axis=1))

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1  2  3  8  9 10 11]
 [ 4  5  6  7 12 13 14 15]]


In [10]:
import numpy as np

arr = np.arange(8).reshape(2,4)
print(arr)

up, down = np.split(arr,2,axis=0)
print(up)
print(down)

left,right = np.split(arr,2,axis=1)
print(left)
print(right)


[[0 1 2 3]
 [4 5 6 7]]
[[0 1 2 3]]
[[4 5 6 7]]
[[0 1]
 [4 5]]
[[2 3]
 [6 7]]


In [13]:
# 도전문제

import numpy as np

b = np.array([[1,1,], [2,2], [3,3]])
a = np.array([1,2,3])
print(b)

print("==============")

print(np.insert(b,1,[1,2,3,],axis=1))

[[1 1]
 [2 2]
 [3 3]]
[[1 1 1]
 [2 2 2]
 [3 3 3]]


In [14]:
import numpy as np
import time

arr_a = np.random.rand(100)
arr_b = np.random.rand(100)
result = np.zeros(100)

start = time.time()
for i in range(len(arr_a)):
    result[i] = arr_a[i] * arr_b[i]
end = time.time()
print('소요시간:', end - start)

# 백터화 연산
start = time.time()
result = arr_a * arr_b
end = time.time();
print('소요시간:', end - start)

소요시간: 0.00028777122497558594
소요시간: 0.000225067138671875


In [15]:
import numpy as np
import time

n = 1000
arr = np.random.rand(n,n)

sum_naive = 0
start = time.time()
for i in range(n):
    for j in range(n):
        sum_naive += arr[i,j]
end = time.time()
print(n, 'x' ,n, "배열의 원소 합", sum_naive, '\n계산 시간: ', end-start)

1000 x 1000 배열의 원소 합 499794.30805128306 
계산 시간:  0.5360891819000244


In [16]:
import numpy as np
import time

n = 1000
arr = np.random.rand(n,n)

start = time.time()
sum_reducation = np.sum(arr, axis=(0,1))
end = time.time();

print(n, 'x' ,n, "배열의 원소 합", sum_reducation, '\n계산 시간: ', end-start)

1000 x 1000 배열의 원소 합 499934.82057750126 
계산 시간:  0.0010175704956054688


In [18]:
import numpy as np

a = np.random.rand(50)
print(a)

[0.60053235 0.78025768 0.13942816 0.54532713 0.66376711 0.6274168
 0.77449963 0.08002866 0.87928128 0.21266543 0.46430523 0.4509025
 0.28220036 0.28121258 0.51241937 0.34166914 0.3032144  0.66237901
 0.23993861 0.67006879 0.60014839 0.22648764 0.63960527 0.34606047
 0.69455791 0.53304166 0.32333145 0.96931044 0.53711985 0.31345743
 0.61491869 0.27296525 0.0133819  0.19149521 0.74169254 0.94782241
 0.68682418 0.21902496 0.81788551 0.7665294  0.10165886 0.84710557
 0.86257189 0.25163412 0.80696093 0.34737752 0.00281232 0.70611558
 0.6907273  0.74641569]


In [20]:
import numpy as np

data = np.arange(1, 51)

def train_8(data, train_r=0.8):
    np.random.shuffle(data)
    split_index = int(len(data) * train_r)
    train_data = data[:split_index]
    test_data = data[split_index:]
    return train_data, test_data


train_data, test_data = train_8(data)

print("train Data:", train_data)
print("test Data:", test_data)


train Data: [45 22 24 43 23  7 20 42 37 48 44 14 18 12  8 16  2 38 32  5 15  6 40  4
 50 30 49 36 41 13 47 34  1  3 31 33 10 25 39 26]
test Data: [27  9 11 19 21 35 28 29 46 17]
